backend:
  name: github
  repo: Kayoken54/getkeystoneps-site
  branch: main
  base_url: super-cherry-d02a.eddie-snyder.workers.dev
  auth_endpoint: auth
  
media_folder: "images"
public_folder: "/images"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "content/site.json"
        label: "Site Content"
        name: "site"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Subtext", name: "subtext", widget: "string" }
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: "Quote", name: "quote", widget: "string" }
              - { label: "Author", name: "author", widget: "string" }
